export default {
  title: 'Cheng Gu',
  subtitle: 'Yuan Tiangang craft · ounce by ounce',
  pageTitle: 'Bone-Weight Reading',
  pageSubtitle: 'Yuan Tiangang method · four-pillar bone weights · 51 fortune verses',
  breadcrumbHome: 'Home',
  breadcrumbCurrent: 'Bone-Weight Reading',
  inputCardTitle: 'Birth Information',
  btn: {
    paipan: 'Weigh the Bones',
    paipanIcon: '◈',
    repaipan: 'Reset',
    repaipanIcon: '◑',
    share: 'Share Card',
    shareIcon: '◈',
    save: 'Save Image',
    saveIcon: '◐',
  },
  resultBanner: {
    title: 'Four Bone Weights',
    subtitle: 'Year · Month · Day · Hour, summed for a lifelong verse',
  },
  skeleton: {
    title: 'Weighing',
    subtitle: 'Reading year pillar, month, day, and hour…',
  },
  section: {
    breakdown: 'Four-Bone Breakdown',
    poem: 'Verse',
  },
  computeError: {
    title: 'Unable to Weigh',
    hint: 'Birth data is invalid or outside the supported 1900-2100 range. Please recheck.',
    retry: 'Re-enter',
  },
  balance: {
    label: 'Bone · Weight',
    labelMn: 'Bone · Weight',
    unit: 'liang',
    breakdown: { year: 'Year', month: 'Month', day: 'Day', hour: 'Hour' },
  },
  placeholder: { displayWeight: '5.1 liang' },
  table: {
    year: 'Year Bone',
    month: 'Month Bone',
    day: 'Day Bone',
    hour: 'Hour Bone',
    totalLabel: 'Four Bones Summed',
  },
  level: {
    top: 'Supreme · Noble',
    high: 'Upper · Eminent',
    middle: 'Middle · Steady',
    low: 'Lower · Toiling',
    bottom: 'Bottom · Frugal',
  },
  poem: {
    seal: 'TT',
    eyebrow: 'Yuan Tiangang Verse',
    meta: 'Classical verse · public edition',
  },
  interpret: {
    title: '◉ Verse Interpretation',
    titleMn: '◆ Verse Interpretation',
    note: 'Note: plain-language interpretation is prepared from public-domain classical texts, for cultural reference only.',
  },
  share: {
    title: 'My Bone-Weight Reading · TT Divination',
    text: 'Yuan Tiangang bone-weight method · four-pillar sums · lifelong verse. Generated by TT Divination.',
  },

  ai: {
    preset: {
      poemMeaning: 'Verse deep-read · line-by-line plain meaning',
      weight: 'Bone weight · what this total represents in life',
      lifeOverview: 'Life overview · early / middle / later trends',
      improvement: 'How to harmonize · what helps & what to avoid',
    },
  },
}
